package interviewTask.retailWebSite.entities.concretes;

public abstract class Card {

	/* Common Variables */
	private int cardId;
	private String cardNumber;
	private String codeOfCardSecurity;
	private int percentageOfDiscount;
	private String cardPassword;
	private int amountOfDiscountUsage;
	private String typeOfCard;
	
	/* Constructor */
	public Card(int cardId, String cardNumber, String codeOfCardSecurity, int percentageOfDiscount, 
			String cardPassword, int amountOfDiscountUsage, String typeOfCard) {
		
		this.cardId = cardId;
		this.cardNumber = cardNumber;
		this.codeOfCardSecurity = codeOfCardSecurity;
		this.percentageOfDiscount = percentageOfDiscount;
		this.cardPassword = cardPassword;
		this.amountOfDiscountUsage = amountOfDiscountUsage;
		this.typeOfCard = typeOfCard;
	}
	
	/* Card Id */
	protected void setCardId(int cardId) {
		this.cardId = cardId;
	}
	public int getCardId() {
		return cardId;
	}
	
	/* Card Number */
	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}
	
	public String getCardNumber() {
		return cardNumber;
	}
	
	/* Card Security Code */
	public void setCodeOfCardSecurity(String codeOfCardSecurity) {
		this.codeOfCardSecurity = codeOfCardSecurity;
	}
	
	public String getCodeOfCardSecurity() {
		return codeOfCardSecurity;
	}
	
	/* Card Password */
	public void setCardPassword(String cardPassword) {
		this.cardPassword = cardPassword;
	}
	
	public String getCardPassword() {
		return cardPassword;
	}
	
	/* Percentage Of Discount */
	public void setPercentageOfDiscount(int percentageOfDiscount ) {
		this.percentageOfDiscount = percentageOfDiscount;
	}
	
	public int getPercentageOfDiscount() {
		return percentageOfDiscount;
	}
	
	/* Amount of discount for usage */
	public void setAmountOfDiscountUsage(int amountOfDiscountUsage) {
		this.amountOfDiscountUsage = amountOfDiscountUsage;
	}
	
	public int getAmountOfDiscountUsage() {
		return amountOfDiscountUsage;
	}
	
	/* Type Of Card */
	public void setTypeOfCard (String typeOfCard) {
		this.typeOfCard = typeOfCard;
	}
	
	public String getTypeOfCard() {
		return typeOfCard;
	}
}

/*
	Description:
	------------
	Card is a superclass. It has a constructor those're 7 parameters. Amount of type of card can be
	generated by this class.
	
	Parameters:
	------------
	cardId: It's identifier numbers. This id  assigned to individual card and  it is identified through it.
	cardNumber: It's sequence of numbers. This is assigned to individual card and It's written front on card.
	codeOfSecurity: It's code of security as understood on name. It's used when you do shopping on internet for security.
	percentageOfDiscount: It's discount. It's used when you do shopping. It can be different on type of card people has.
	cardPassword: It'can be difference on each card ,and It's used either doing shopping and getting money on atm.
	
	Return:
	---------
	None
	*/
